### ISSUE TITLE
Replace Shell with Command

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/bedita#1987]
Since `Shell` class is deprecated and will be removed from Cake 5.x - see https://book.cakephp.org/4/en/console-commands/shells.html we should:

* replace `Shell` with `[Command Objects](https://book.cakephp.org/4/en/console-commands/commands.html)` where possible 
* replace shell `Tasks` with with `Command Objects` or [Command Helpers](https://book.cakephp.org/4/en/console-commands/input-output.html#command-helpers) where possibile

"BEdita\Core\Shell" shells and tasks:

 - [x] BeditaShell [deprecated by #2111 / BeditaCommand instead]
   - CheckApiKeyTask
   - CheckFilesystemTask
   - CheckSchemaTask
   - InitSchemaTask
   - SetupAdminUserTask
   - SetupConnectionTask 
 - [x] DbAdminShell [deprecated by #2111 / DbAdminCommand instead]
   - CheckSchemaTask 
   - InitSchemaTask 
 - [x] Shell\JobsShell [deprecated by #2052 / JobsCommand instead]
 - [x] ResourcesShell [deprecated by #2110 / ResourcesCommand instead, or ResourcesAddCommand, ResourcesModifyCommand, ResourcesRemoveCommand, ResourcesListCommand]
 - [x] StreamsShell [deprecated by #2108 / StreamsCommand instead]

**Comment by didoda** [comment]
closed with #1993, #2052, #2108, #2110, #2111
