### ISSUE TITLE
Multimedia "media types" to BEdita Object

### ISSUE THREAD

**Issue by batopa** [bedita/bedita#347]
Multimedia module handles some BEdita object types that can be detailed through **media types** that are special fixed categories defined in configuration in ```bedita.ini.php```.

The current situation is:

#### Object types
Image, Video, Audio, BEFile

#### Configuration category types
```php
$config['mediaTypes'] = array('image','video','audio','archive','text','spreadsheet','presentation','drawing','chart','formula','application');
```

**To improve flexibility and to use categories in the standard way** also in Multimedia module it needs a renovation replacing category types with BEdita Object.

#### Todo

- [ ] all "mediaTypes" become BEdita Object. Image, Video, Audio are already present, for other type add a Model simple as BEFile
- [ ] change the filter to filter by object type instead of categories
- [ ] change the media type chooser (radio button) inside multimedia detail to object type chooser and manage the changes of object type in MultimediaController.
- [ ] evaluate if some fields in images and videos tables can be moved in streams table to generalize multimedia object types (for example thumbnail in videos table could be useful for all multimedia object types)
- [ ] prepare a migration shell script to map old media types to new object types.
